#!/usr/bin/env node

const faktory = require('../');
const concurrency = Number(process.argv[2]) || 1;

(async () => {

  let completed = 0;
  const time = process.hrtime();
  let manager;

  const finish = () => {
    completed += 1;
    if (completed === 30000) {
      const diff = process.hrtime(time);
      const duration = diff[0] + (diff[1] / 1e9);

      console.log(`
processed: ${completed}
concurrency: ${manager.concurrency}
duration: ${duration}s
jobs/s: ${Math.round(completed / duration, 2)}
`);
      manager.stop();
    }
  };

  faktory.register('MyJob', async () => {
    await new Promise(resolve => setTimeout(resolve, 0));
    finish();
  });

  manager = await faktory.work({ concurrency });

})();
