#!/usr/bin/env node

const faktory = require('../');
const concurrency = Number(process.argv[2]);

(async () => {

  let completed = 0;
  const time = process.hrtime();

  faktory.register('MyJob', async () => {
    completed += 1;
    if (completed === 30000) {
      const diff = process.hrtime(time);
      const duration = diff[0] + (diff[1] / 1e9);

      console.log(`
Benchmark Results:

Jobs processed: ${completed}
Concurrency: ${concurrency}

Duration: ${duration}s
Jobs/s: ${Math.round(completed / duration, 2)}
`);
      process.exit(0);
    }
  });

  await faktory.work({ concurrency });

})();
